name: 'Upload Release Assets'
description: 'Upload release assets to an existing release in your repository, including glob support'
author: 'alexellis'
inputs:
  asset_paths:
    description: 'The paths to the assets you want to upload as a JSON array. You can use a glob pattern.'
    required: true
  tag_name:
    description: 'The name of the tag you want to upload assets to. Defaults to the tag of the release that triggered the workflow.'
    required: false
  skip_existing:
    description: 'Whether to skip uploading assets that already exist in the release. Defaults to false.'
    required: false
outputs:
  browser_download_urls:
    description: 'The URL users can navigate to in order to download the uploaded asset'
runs:
  using: 'node20'
  main: 'dist/index.js'
branding:
  icon: 'package'
  color: 'gray-dark'

